### ISSUE TITLE
Worker RPC is accessible over the network without authentication

### ISSUE THREAD

**Issue by enolan** [janestreet/rpc_parallel#7]
Local RPC workers listen on `0.0.0.0`, which is accessible over the network in the absence of a firewall. An attacker who can connect to the port can call arbitrary RPCs. The situation would be improved by listening on `127.0.0.1` instead, which is only accessible from the local machine, but it's not implausible for an attacker to be able to access that interface. Machines may have multiple users that are expected to be sandboxed from each other, or an attacker may exploit the user into sending data to the local network via e.g. a malicious web page. See [here](https://www.forcepoint.com/sites/default/files/resources/files/report-attacking-internal-network-en_0.pdf) for some info on this sort of thing.

The best option I see is to A) only listen on localhost and B) for workers to require that RPC calls come along with the correct `Worker_id.t`. That's a UUID, and hopefully generated securely. The legitimate master should be the only one with that knows the correct UUID.

I also thought about using Unix pipes as the RPC transport instead of TCP, since child processes can inherit fds from the parent, but that may be more complicated. Not sure, I haven't dug into the code enough to decide yet.

**Comment by jakemcarthur** [comment]
Unconditionally listening on localhost is not an option because Rpc_parallel is supposed to work in distributed environments across multiple hosts. It is even possible to start a worker and then send it to another worker over Rpc so that the other worker can connect to it. If you started the worker locally, binding to localhost, a worker on another host would not be able to connect to it.

We could make this controllable, however, and then it's just on client code to ensure that all workers will be able to communicate with each other. I think we should expose some optional parameters allowing you to specify the interfaces and ports to listen on.

I agree that checking the worker ids would be a good idea, to prevent certain kinds of mistakes, but I don't think it's much of a security measure. All it takes to defeat it is to sniff packets or convince an existing process to send you an id. For authentication, we're thinking of offering some interface to use your own authentication mechanism upon connecting. I think this is the only way it can work in a variety of environments with different authentication mechanisms available.

**Comment by jakemcarthur** [comment]
It is now possible to supply a custom backend, and we currently have an unauthenticated backend and a backend that uses Kerberos for authentication.
